[package]
name = "client"
version = "0.1.0"
authors = ["Dragan <d.novakovic1810@yahoo.com>"]
edition = "2018"

[dependencies]
strum = "0.9"
strum_macros = "0.9"
serde = "1"
serde_derive = "1"
stdweb = "0.4.2"
log = "0.4"
web_logger = "0.1"
yew = {git = "https://github.com/DenisKolodin/yew"}